# Generated by Django 5.0.1 on 2024-02-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("E-commerce", "E-commerce"),
                    ("Blog site", "Blog site"),
                    ("Portfolio site", "Portfolio site"),
                    ("Tutorial site", "Tutorial site"),
                    ("LMS site", "LMS site"),
                ],
                default="default_category",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(upload_to="main_app/project_images/"),
        ),
    ]
